version: '3'
services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
    environment:
      - WDS_SOCKET_HOST=5050
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true=value
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  client:
    build: ./client
    ports:
      - 8080:3000
    command: npm run dev
    volumes:
      - ./client/src/:/app/src/
    environment:
      - WDS_SOCKET_HOST= 8080
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true=value